### ISSUE TITLE
error when installing the sof

### ISSUE THREAD

**Issue by chen318liang** [giuliaguidi/bella#1]
gcc -O3 -fopenmp -c -o bound.o kmercode/bound.cpp
In file included from /usr/include/c++/4.9/array:35:0,
                 from kmercode/bound.cpp:11:
/usr/include/c++/4.9/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
make: *** [bound.o] Error 1

how can I solve the errors? thanks!

**Comment by giuliaguidi** [comment]
If you could update your compiler to >= gcc 6.1.0, the issue should be solved. Please, let me know if it works.

**Comment by chen318liang** [comment]
ok! thanks very much! I have sloved this problem!
