### ISSUE TITLE
Too much memory requested

### ISSUE THREAD

**Issue by TorHou** [giuliaguidi/bella#2]
Hi,

I've been trying to use bella b150701e217ce29cddf83b53f987f6380a09f745 to assemble a small portion of the human genome. Whenever I try to use it though I run into the issue that bella apparently sometimes wants insane amounts of memory. 

> ./bella -k 13 -i input.fastq -o test-bella -d 3

sometimes gives 

> @id1 : 133599645 MB
ACGT .... : 133599645 MB
: 133599645 MB

When I let this run, the memory fills up until I have to restart my computer.
Only sometimes i get somethig more feasible (with the exact same command, mind you) :

> @id1 : 3 MB
ACGT .... : 3 MB
: 3 MB

I've tried this with different depth settings and with different k-mer lengths, but the problem seems to always occur.

**Comment by giuliaguidi** [comment]
Hi Torsten,

BELLA requires a text file containing the path to the input fastq file(s) as the argument for the -i option.
Here's an example: [input-example.txt](https://github.com/giuliaguidi/bella/files/2620924/input-example.txt)
 
If you would run out of memory during the overlapping phase (after sparse matrix construction), you may try to enable the flags in mtspgemm2017/overlapping.h: #DEFINE RAM and #DEFINE LINUX or OSX (based on your machine). These flags would allow you to use only the available RAM on your machine to compute the overlaps. 

Please let me know if you encounter other issues,
Best,
Giulia

**Comment by TorHou** [comment]
Hi Guilia,

thank you for the quick response. Now that worked :) . The helptext for `-i` is a bit counter-intuitive for me, maybe something like `-i <text file listing all input fastq files> ` would be better ?

I'm looking forward to using BELLA as intended ;)

Best,
Torsten

**Comment by giuliaguidi** [comment]
Great! 
I updated the README following your feedback.

Best,
Giulia
